### ISSUE TITLE
No such file or directory: 'target.board.devices.flash.img'

### ISSUE THREAD

**Issue by geitnert** [GreenWaves-Technologies/nn_menu#5]
Bonjour,

L'erreur **No such file or directory: 'WildCount/nn_menu/starters/face_detection/BUILD/GAP8_V2/GCC_RISCV/target.board.devices.flash.img'** survient lors de la compilation de la plupart des exemple de nn_menu.

Savez-vous d'où pourrais venir l'erreur ?

Exemple de stacktrace pour l'exemple face_detection :

`LAPTOP:~/WildCount2/nn_menu/ingredients/face_detection$ make PMSIS_OS=freertos platform=board io=host all -j
[...]
Traceback (most recent call last):
File "/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/tools/gapy/gapy", line 162, in <module> main()
  File "/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/tools/gapy/gapy", line 152, in main
    operationFunc(args, config)
  File "/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/tools/gapy/run.py", line 154, in operationFunc
    status = runner.run()
  File "/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/tools/gapy/runner/default_runner.py", line 40, in run
    if self.flash() != 0:
  File "/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/tools/gapy/runner/board/board_runner.py", line 56, in flash
    image_size = os.path.getsize(image)
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/geitnert/Polytech/4a/Stage/WildCount2/nn_menu/starters/face_detection/BUILD/GAP8_V2/GCC_RISCV/target.board.devices.flash.img'
make: *** [/home/geitnert/Polytech/4a/Stage/WildCount2/gap_sdk/rtos/freeRTOS/vendors/gwt/rules/freeRTOS_rules.mk:410: flash] Error 1
`

**Comment by Pafrak** [comment]
Hello geitnert,
 could you send your full trace?

**Comment by Pafrak** [comment]
close due to inactivity, in case the issue is still there please reopen it.
